### ISSUE TITLE
Add code of conduct

### ISSUE THREAD

**Issue by gridhead** [t0xic0der/mdapi#54]
In the spirit of getting more contributors to the project, the above document would be appreciated.

**Comment by VividhPandey003** [comment]
Hey I'm a beginner to Open Source and would love to work on this issue. Could you please assign this issue to me under Hacktoberfest

**Comment by gridhead** [comment]
There you go, @VividhPandey003. Happy Hacktoberfest!

Please refer to https://www.contributor-covenant.org/version/2/1/code_of_conduct/code_of_conduct.md for the code of conduct documentation.

**Comment by VividhPandey003** [comment]
Hey thanks a lot for assigning me this issue. I'll submit a PR as soon as I can.
Also I had a doubt regarding the reference doc you shared. Should I add more to it or is this the basic information we need for the repository. 🤔

**Comment by gridhead** [comment]
@VividhPandey003, this is the basic information that we need in the repository. Of course, adding atop it helps but we need to be sure that the document should be exhaustive and complete in itself.

**Comment by VividhPandey003** [comment]
@t0xic0der So basically I just need to copy the doc you provided and make a CODE_OF_CONDUCT.md file for it because I read it right now and everything sounds perfect

**Comment by VividhPandey003** [comment]
Hey @t0xic0der, I've made a Pull Request. Could you please review it and tell me if I need to make any changes.😊
