### ISSUE TITLE
Add contribution guidelines to the project

### ISSUE THREAD

**Issue by gridhead** [t0xic0der/mdapi#56]
In the spirit of getting more contributors to the project, the above document would be appreciated.

**Comment by VividhPandey003** [comment]
Hey I'm a beginner to Open Source and would love to work on this issue. Could you please assign this issue to me under Hacktoberfest⭐️

**Comment by gridhead** [comment]
@VividhPandey003, I am restricting one issue assignment at any point in time for a repository and as https://github.com/t0xic0der/mdapi/issues/54#issuecomment-1261670857 was already assigned to you, I would suggest you to complete that first before picking up anything else.

**Comment by Ank-22** [comment]
Assign to me

**Comment by gridhead** [comment]
Here you go, @Ank221199. Happy Hacktoberfest!

You should be able to find the reference documents here https://opensource.com/life/16/3/contributor-guidelines-template-and-tips

**Comment by VividhPandey003** [comment]
> @VividhPandey003, I am restricting one issue assignment at any point in time for a repository and as [#54 (comment)](https://github.com/t0xic0der/mdapi/issues/54#issuecomment-1261670857) was already assigned to you, I would suggest you to complete that first before picking up anything else.

Yes sure. Thanks a lot for assigning that to me😊

**Comment by gridhead** [comment]
Fixed via #63. Thanks, @Ank221199.
